services:
  - type: web
    name: hamilik
    runtime: static
    repo: https://github.com/dalitamer/hamilik
    branch: main
    rootDir: react-app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
